name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.0

permissions:
  contents: write  # Allows creating releases

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Extract version without "v" using PowerShell
        id: version
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo $version
          echo "full_without_prefix=$version" >> $GITHUB_OUTPUT
        

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Clang
        run: |
          choco install llvm -y
          clang --version

      - name: Run build.ps1
        shell: pwsh
        run: ./build.ps1 -Version ${{ steps.version.full_without_prefix }}

      - name: Create GitHub Release and Upload .nupkg
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token automatically
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload .nupkg to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./window-switcher.${{ steps.version.full_without_prefix }}.nupkg
          asset_name: window-switcher.${{ steps.version.full_without_prefix }}.nupkg
          asset_content_type: application/octet-stream
